project:
  type: website

website:
  title: "Open Scholarship Community Sheffield"
  site-url: https://ns-rse.github.io/osc-sheff
  description: "Progress in establishing an Open Scholarship Community in Sheffield"
